### ISSUE TITLE
hot reload failed caused by vm service method execution was hanged 

### ISSUE THREAD

**Issue by lvscar** [Jaguar-dart/jaguar_hotreload#2]
I'm trying to migrate the wonderful jaguar_hotreload code to Dart2 compatible.

But in the process , I was got stuck by a potential vm service bug in Dart2 ( 2.0.0-dev.67.0).

I have submitted an issue to the dart [vm_service_drivers project](https://github.com/dart-lang/vm_service_drivers/issues/180).

@tejainece Do you think it's meaningful to implement a sub process restarting based hot reload function?

**Comment by tejainece** [comment]
Definitely!

**Comment by lvscar** [comment]
I found a third part workaround for implementing a sub process restarting based hot reload. Using [watchexec](https://github.com/mattgreen/watchexec) .
> $ watchexec -e dart -r dart bin/main.dart

Look forward to switch back to dart vm based hot reload in the future.

**Comment by tejainece** [comment]
I will work on porting `jaguar_hotreload` package to Dart 2.
